FROM node:20

WORKDIR /app

# copy package files
COPY package*.json ./

# install all deps
RUN npm install

# copy full project
COPY . .

# build the entire monorepo
RUN npm run build:post

# run ONLY api-gateway
CMD ["node", "dist/apps/post/main.js"]